In [9]:
import numpy as np

In [19]:
A = np.random.randint(-2, 2, size=(3, 3, 2))
B = np.random.randint(-2, 2, size=(3, 2, 4))
A, B

(array([[[-2, -2],
         [ 0,  1],
         [ 1, -1]],
 
        [[ 1, -1],
         [-1, -1],
         [-2,  0]],
 
        [[ 0,  0],
         [-2,  0],
         [-2,  1]]]),
 array([[[ 1,  0, -1, -1],
         [-2, -1,  0,  0]],
 
        [[-1, -2, -1,  1],
         [ 1, -1, -1, -1]],
 
        [[-2,  0,  0,  1],
         [-1, -2,  1,  1]]]))

In [21]:
A.shape

(3, 3, 2)

In [20]:
C = np.matmul(A, B)
C

array([[[ 2,  2,  2,  2],
        [-2, -1,  0,  0],
        [ 3,  1, -1, -1]],

       [[-2, -1,  0,  2],
        [ 0,  3,  2,  0],
        [ 2,  4,  2, -2]],

       [[ 0,  0,  0,  0],
        [ 4,  0,  0, -2],
        [ 3, -2,  1, -1]]])

In [23]:
C.reshape((-1, 32))
C

ValueError: cannot reshape array of size 36 into shape (120)