In [2]:
import numpy as np

In [8]:
A = np.random.randint(-2, 2, size=(3, 3, 2))
B = np.random.randint(-2, 2, size=(3, 2, 4))
A, B

(array([[[-1, -2],
         [ 1, -2],
         [ 0, -2]],
 
        [[ 1, -1],
         [-1,  1],
         [-1,  1]],
 
        [[-1,  1],
         [ 1,  0],
         [-2,  1]]]),
 array([[[-2,  0,  0,  0],
         [-1, -2, -1, -2]],
 
        [[ 0,  0,  1, -1],
         [ 1,  0, -2,  1]],
 
        [[-2,  0,  0, -1],
         [ 1,  0, -1,  0]]]))

In [21]:
A.shape

(3, 3, 2)

In [27]:
C = np.matmul(A, B)
C, C.shape

(array([[[ 2,  2,  2,  2],
         [-2, -1,  0,  0],
         [ 3,  1, -1, -1]],
 
        [[-2, -1,  0,  2],
         [ 0,  3,  2,  0],
         [ 2,  4,  2, -2]],
 
        [[ 0,  0,  0,  0],
         [ 4,  0,  0, -2],
         [ 3, -2,  1, -1]]]),
 (3, 3, 4))

In [40]:
C = C.reshape((-1, 3, 6))
C, C.shape

(array([[[ 2,  2,  2,  2, -2, -1],
         [ 0,  0,  3,  1, -1, -1],
         [-2, -1,  0,  2,  0,  3]],
 
        [[ 2,  0,  2,  4,  2, -2],
         [ 0,  0,  0,  0,  4,  0],
         [ 0, -2,  3, -2,  1, -1]]]),
 (2, 3, 6))

In [12]:
a = np.array([1,0,0,1,0])
a.resize(4)
a

array([1, 0, 0, 1])

In [4]:
a = np.array([1,0,0,1,0])
a.reshape(4)
a

ValueError: cannot reshape array of size 5 into shape (4,)

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a@b)

[[19 22]
 [43 50]]


In [6]:
from tinygrad import Tensor
a = Tensor.rand((2, 3))
print(len(a.shape)

(2, 3)
