In [92]:
from tinygrad import Tensor, dtypes

In [14]:
a = Tensor.eye(3)
print(a.numpy())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [91]:
dim = 3
b = Tensor.full((dim, 1), 1)
# args = ((0,0),(0,dim))
# print(tuple([(p[0], s+p[1]) for s,p in zip(b.shape, args)]))
# print(tuple(x if x is not None else (1,1) for x in args))
print(b)
print(f"{b.numpy()} full")
# arg = ((top, bottom),(left, right))
b = b.pad(((0,0),(0,dim)))
print(b)
print(f"{b.numpy()} pad")
b = b.reshape(dim*(dim+1))
print(b)
print(f"{b.numpy()} reshape")
b = b.shrink(((0, dim*dim),))
print(b)
print(f"{b.numpy()} shrink")
b = b.reshape(dim, dim)
print(b)
print(f"{b.numpy()} reshape")

<Tensor <LB METAL (3, 1) contig:False ShapeTracker(views=(View(shape=(3, 1), strides=(0, 0), offset=0, mask=None, contiguous=False),))> on METAL with grad None>
[[1]
 [1]
 [1]] full
<Tensor <LB METAL (3, 4) contig:False ShapeTracker(views=(View(shape=(3, 4), strides=(0, 0), offset=0, mask=((0, 3), (0, 1)), contiguous=False),))> on METAL with grad None>
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]] pad
<Tensor <LB METAL (12,) contig:False ShapeTracker(views=(View(shape=(3, 4), strides=(0, 0), offset=0, mask=((0, 3), (0, 1)), contiguous=False), View(shape=(12,), strides=(1,), offset=0, mask=None, contiguous=True)))> on METAL with grad None>
[1 0 0 0 1 0 0 0 1 0 0 0] reshape
<Tensor <LB METAL (9,) contig:False ShapeTracker(views=(View(shape=(3, 4), strides=(0, 0), offset=0, mask=((0, 3), (0, 1)), contiguous=False), View(shape=(9,), strides=(1,), offset=0, mask=None, contiguous=True)))> on METAL with grad None>
[1 0 0 0 1 0 0 0 1] shrink
<Tensor <LB METAL (3, 3) contig:False ShapeTracker(views=(View(s

In [104]:
a = Tensor([1,1,1,1,1])
b = Tensor([1,1]).pad(((0,3),))
print(a)
print(b)
print(a.numpy(), b.numpy())
c = a*b
print(c)
print(c.numpy())


<Tensor <LB METAL (5,) contig:True (<LoadOps.COPY: 3>, None)> on METAL with grad None>
<Tensor <LB METAL (5,) contig:False ShapeTracker(views=(View(shape=(5,), strides=(1,), offset=0, mask=((0, 2),), contiguous=False),))> on METAL with grad None>
[1 1 1 1 1] [1 1 0 0 0]
<Tensor <LB METAL (5,) contig:True (<BinaryOps.MUL: 3>, None)> on METAL with grad None>
[1 1 0 0 0]


In [109]:
a = Tensor([1, 2, 3, 4, 5])
print(a.mean().numpy(), a.var().numpy(), a.std().numpy())

3.0 2.5 1.5811388


In [120]:
# mean
m = a.sum()/a.numel()
assert a.mean().numpy() == m.numpy()

# var
correction = 1
ss = (a- m).square().sum()
v = ss.div(max(0, a.numel() - correction))
assert v.var().numpy() == v.numpy()

# std
std = v.sqrt()
print(std.numpy())
assert a.std().numpy() == std.numpy()

AssertionError: 

2.5


1.5811388
